
package webservertest.ws2;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuerySysRes", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", wsdlLocation = "http://10.102.102.101/ams/account_service/services/QuerySysRes?wsdl")
public class QuerySysRes
    extends Service
{

    private final static URL QUERYSYSRES_WSDL_LOCATION;
    private final static WebServiceException QUERYSYSRES_EXCEPTION;
    private final static QName QUERYSYSRES_QNAME = new QName("http://sysres.scgk.webservice.server.iam.ultrapower.com", "QuerySysRes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.102.102.101/ams/account_service/services/QuerySysRes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYSYSRES_WSDL_LOCATION = url;
        QUERYSYSRES_EXCEPTION = e;
    }

    public QuerySysRes() {
        super(__getWsdlLocation(), QUERYSYSRES_QNAME);
    }

    public QuerySysRes(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYSYSRES_QNAME, features);
    }

    public QuerySysRes(URL wsdlLocation) {
        super(wsdlLocation, QUERYSYSRES_QNAME);
    }

    public QuerySysRes(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYSYSRES_QNAME, features);
    }

    public QuerySysRes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuerySysRes(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuerySysResPortType
     */
    @WebEndpoint(name = "QuerySysResHttpPort")
    public QuerySysResPortType getQuerySysResHttpPort() {
        return super.getPort(new QName("http://sysres.scgk.webservice.server.iam.ultrapower.com", "QuerySysResHttpPort"), QuerySysResPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySysResPortType
     */
    @WebEndpoint(name = "QuerySysResHttpPort")
    public QuerySysResPortType getQuerySysResHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sysres.scgk.webservice.server.iam.ultrapower.com", "QuerySysResHttpPort"), QuerySysResPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYSYSRES_EXCEPTION!= null) {
            throw QUERYSYSRES_EXCEPTION;
        }
        return QUERYSYSRES_WSDL_LOCATION;
    }

}
