
package webservertest.ws2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuerySysResPortType", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuerySysResPortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
    @RequestWrapper(localName = "getMultPwd", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.GetMultPwd")
    @ResponseWrapper(localName = "getMultPwdResponse", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.GetMultPwdResponse")
    public String getMultPwd(
            @WebParam(name = "in0", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
                    String in0);

    /**
     *
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
    @RequestWrapper(localName = "getPwd", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.GetPwd")
    @ResponseWrapper(localName = "getPwdResponse", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.GetPwdResponse")
    public String getPwd(
            @WebParam(name = "in0", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
                    String in0);

    /**
     *
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
    @RequestWrapper(localName = "searchRes", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.SearchRes")
    @ResponseWrapper(localName = "searchResResponse", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com", className = "com.ultrapower.iam.server.webservice.scgk.sysres.SearchResResponse")
    public String searchRes(
            @WebParam(name = "in0", targetNamespace = "http://sysres.scgk.webservice.server.iam.ultrapower.com")
                    String in0);

}
